/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.6.1/userguide/tutorial_java_projects.html
 */

plugins {
    java
    //application
}

repositories {
}

dependencies {
    // This dependency is used by the application.
    implementation(project(":quicksort-tracer"))
}
