/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quicksort;

import quicksort.Quicksort;

public class App {
    public static void main(String[] argv) {
        int[] array = new int[argv.length];
        for (int i = 0; i < argv.length; i++) {
            array[i] = Integer.valueOf(argv[i]).intValue();
            System.out.printf("array[%d] = %d\n", i, array[i]);
        }

        Quicksort.sort(array);

        System.out.printf("Sorted array:\n");
        for (int i = 0; i < argv.length; i++) {
            System.out.printf("array[%d] = %d\n", i, array[i]);
        }
    }
}
